/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemapaquetes.ui.administradorUI;

import javax.swing.JDesktopPane;
import javax.swing.JMenuItem;

/**
 *
 * @author asael
 */
public class AdminView extends javax.swing.JFrame {

    /**
     * Creates new form AdminUI
     */
    public AdminView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        DeskAdminFrame = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itmAddUser = new javax.swing.JMenuItem();
        itmDeshabilitarUser = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itmDestinos = new javax.swing.JMenuItem();
        itmCrearRuta = new javax.swing.JMenuItem();
        itmDisableRuta = new javax.swing.JMenuItem();
        menuPrecios = new javax.swing.JMenu();
        itmPreciosTarifas = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DeskAdminFrameLayout = new javax.swing.GroupLayout(DeskAdminFrame);
        DeskAdminFrame.setLayout(DeskAdminFrameLayout);
        DeskAdminFrameLayout.setHorizontalGroup(
            DeskAdminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );
        DeskAdminFrameLayout.setVerticalGroup(
            DeskAdminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        jMenu1.setText("Usuarios");

        itmAddUser.setText("Agregar Usuario");
        jMenu1.add(itmAddUser);

        itmDeshabilitarUser.setText("Deshabilitar Usuario");
        jMenu1.add(itmDeshabilitarUser);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Rutas");

        itmDestinos.setText("Destinos");
        jMenu2.add(itmDestinos);

        itmCrearRuta.setText("CrearRuta");
        jMenu2.add(itmCrearRuta);

        itmDisableRuta.setText("Deshabilitar Ruta");
        jMenu2.add(itmDisableRuta);

        jMenuBar1.add(jMenu2);

        menuPrecios.setText("Tarifas");

        itmPreciosTarifas.setText("Ver precios y tarifas");
        menuPrecios.add(itmPreciosTarifas);

        jMenuBar1.add(menuPrecios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DeskAdminFrame)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DeskAdminFrame)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DeskAdminFrame;
    private javax.swing.JMenuItem itmAddUser;
    private javax.swing.JMenuItem itmCrearRuta;
    private javax.swing.JMenuItem itmDeshabilitarUser;
    private javax.swing.JMenuItem itmDestinos;
    private javax.swing.JMenuItem itmDisableRuta;
    private javax.swing.JMenuItem itmPreciosTarifas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuPrecios;
    // End of variables declaration//GEN-END:variables

    public JDesktopPane getDeskAdminFrame() {
        return DeskAdminFrame;
    }

    public JMenuItem getItmAddUser() {
        return itmAddUser;
    }

    public JMenuItem getItmDeshabilitarUser() {
        return itmDeshabilitarUser;
    }

    public JMenuItem getItmCrearRuta() {
        return itmCrearRuta;
    }

    public JMenuItem getItmDestinos() {
        return itmDestinos;
    }

    public JMenuItem getItmPreciosTarifas() {
        return itmPreciosTarifas;
    }
}
