/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemapaquetes.ui.administradorUI;

import javax.swing.JButton;
import javax.swing.JComboBox;
import org.jdesktop.observablecollections.ObservableList;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import sistemapaquetes.model.ListasObservables;

/**
 *
 * @author asael
 */
public class DisableUserView extends javax.swing.JInternalFrame {
    
    private ListasObservables observableList;
    private ObservableList<String> dpiListObservable;
    
    /**
     * Creates new form DisableUserView
     */
    public DisableUserView() {
        observableList = ListasObservables.getInstance();
        dpiListObservable = observableList.getDpiListObservable();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLabel1 = new javax.swing.JLabel();
        cbDPIUsers = new javax.swing.JComboBox<>();
        btnDeshabilitar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setTitle("Deshabilitar Usuario");

        jLabel1.setText("DPI Usuario");

        AutoCompleteDecorator.decorate(cbDPIUsers);
        cbDPIUsers.setEditable(true);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${dpiListObservable}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, cbDPIUsers);
        bindingGroup.addBinding(jComboBoxBinding);

        btnDeshabilitar.setText("Deshabilitar");

        btnCerrar.setText("Cerrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbDPIUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnDeshabilitar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrar)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbDPIUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeshabilitar)
                    .addComponent(btnCerrar))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnDeshabilitar;
    private javax.swing.JComboBox<String> cbDPIUsers;
    private javax.swing.JLabel jLabel1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setVisible(boolean visibility){
        if (visibility) {
            observableList.reloadListados();
        }
        super.setVisible(visibility);
    }

    public JButton getBtnDeshabilitar() {
        return btnDeshabilitar;
    }

    public JButton getBtnCerrar() {
        return btnCerrar;
    }

    public JComboBox<String> getCbDPIUsers() {
        return cbDPIUsers;
    }

    public ObservableList<String> getDpiListObservable() {
        return dpiListObservable;
    }

    public void setDpiListObservable(ObservableList<String> dpiListObservable) {
        this.dpiListObservable = dpiListObservable;
    }
}
