/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemapaquetes.ui.recepcionistaUI;

import javax.swing.JDesktopPane;
import javax.swing.JMenuItem;

/**
 *
 * @author asael
 */
public class RecepcionistaView extends javax.swing.JFrame {

    /**
     * Creates new form RecepcionistaView
     */
    public RecepcionistaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DeskRecepcion = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenu1 = new javax.swing.JMenu();
        itmClientes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itmAddPaquete = new javax.swing.JMenuItem();
        itmRetiroP = new javax.swing.JMenuItem();
        itmConsultarL = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DeskRecepcionLayout = new javax.swing.GroupLayout(DeskRecepcion);
        DeskRecepcion.setLayout(DeskRecepcionLayout);
        DeskRecepcionLayout.setHorizontalGroup(
            DeskRecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );
        DeskRecepcionLayout.setVerticalGroup(
            DeskRecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );

        JMenu1.setText("Clientes");

        itmClientes.setText("Ingreso Clientes");
        JMenu1.add(itmClientes);

        jMenuBar1.add(JMenu1);

        jMenu2.setText("Paquetes");

        itmAddPaquete.setText("Ingresar Paquete");
        jMenu2.add(itmAddPaquete);

        itmRetiroP.setText("Registrar Retiro");
        jMenu2.add(itmRetiroP);

        itmConsultarL.setText("Consultar Localizacion");
        jMenu2.add(itmConsultarL);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DeskRecepcion)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DeskRecepcion)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DeskRecepcion;
    private javax.swing.JMenu JMenu1;
    private javax.swing.JMenuItem itmAddPaquete;
    private javax.swing.JMenuItem itmClientes;
    private javax.swing.JMenuItem itmConsultarL;
    private javax.swing.JMenuItem itmRetiroP;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    public JDesktopPane getDeskRecepcion() {
        return DeskRecepcion;
    }

    public JMenuItem getItmAddPaquete() {
        return itmAddPaquete;
    }

    public JMenuItem getItmClientes() {
        return itmClientes;
    }

    public JMenuItem getItmConsultarL() {
        return itmConsultarL;
    }

    public JMenuItem getItmRetiroP() {
        return itmRetiroP;
    }
}
